[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
async-timer = "0.7.4"
bitvec = "1.0.1"
futures = "0.3.30"
sdl2 = "0.36.0"
smol = "2.0.0"
ux = "0.1.6"
log = "0.4"
env_logger = "0.11"
fastrand = "2.1.1"
